// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDrfng98SdcB9JX4SMJX7mOnDmQNLGH9M',
    appId: '1:403024144797:web:60a407d3bdfc18b7f3e774',
    messagingSenderId: '403024144797',
    projectId: 'the-notifier-80609',
    authDomain: 'the-notifier-80609.firebaseapp.com',
    storageBucket: 'the-notifier-80609.appspot.com',
    measurementId: 'G-PG31740Z7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jFvlCUMcoZ2OLXeX0hCrCr2Pigo9HmI',
    appId: '1:403024144797:android:d0a729bc4487f812f3e774',
    messagingSenderId: '403024144797',
    projectId: 'the-notifier-80609',
    storageBucket: 'the-notifier-80609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdZ8iYc_z7FgwSo4vHKVCq280zBMM-r4',
    appId: '1:403024144797:ios:26d69519b0508581f3e774',
    messagingSenderId: '403024144797',
    projectId: 'the-notifier-80609',
    storageBucket: 'the-notifier-80609.appspot.com',
    iosBundleId: 'com.example.theNotfiers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABdZ8iYc_z7FgwSo4vHKVCq280zBMM-r4',
    appId: '1:403024144797:ios:f2f19fa3d17e3865f3e774',
    messagingSenderId: '403024144797',
    projectId: 'the-notifier-80609',
    storageBucket: 'the-notifier-80609.appspot.com',
    iosBundleId: 'com.example.theNotfiers.RunnerTests',
  );
}
